services:
  - docker
dist: xenial
language: python
python:
  - "3.7"
install:
  - docker pull python:3.7-stretch
script:
  - docker run -it --rm -v $(pwd):/einops/ python:3.7-stretch bash -c 'python /einops/test.py'
