services:
  - docker
dist: xenial
language: generic
matrix:
  include:
  - name: python3.5
    env: DOCKERIMAGE=python:3.5-stretch
  - name: python3.7
    env: DOCKERIMAGE=python:3.7-stretch
install:
  - docker pull $DOCKERIMAGE
script:
  - docker run -it --rm -v $(pwd):/einops/ $DOCKERIMAGE bash -c 'python /einops/test.py'
